ant-media/Plugins

TensorflowPlugin/src/main/java/io/antmedia/plugin/AVFramePool.java
TensorflowPlugin/src/main/java/io/antmedia/plugin/IDeepLearningProcessor.java
TensorflowPlugin/src/main/java/io/antmedia/plugin/TensorflowFrameListener.java
TensorflowPlugin/src/main/java/io/antmedia/plugin/TensorflowPlugin.java
TensorflowPlugin/src/main/java/io/antmedia/plugin/Utils.java
TensorflowPlugin/src/main/java/io/antmedia/plugin/tensorflow/detection/TFObjectDetector.java
TensorflowPlugin/src/main/java/io/antmedia/plugin/tensorflow/detection/TensorFlowDetector.java
TensorflowPlugin/src/main/java/io/antmedia/plugin/tensorflow/recognition/TensorFlowRecognizer.java
TensorflowPlugin/src/main/java/io/antmedia/rest/RestService.java

https://github.com/ant-media/Ant-Media-Server/issues/3763

Run tensorflow in realtime

---

FilterPlugin/src/main/java/io/antmedia/plugin/MCUManager.java

https://github.com/ant-media/Ant-Media-Server/issues/3787

Call filter update immediately when someone left the room

---

FilterPlugin/src/main/java/io/antmedia/filter/FilterAdaptor.java
FilterPlugin/src/main/java/io/antmedia/filter/utils/FilterGraph.java

https://github.com/ant-media/Ant-Media-Server/issues/3804

Fix the sync issue between webrtc and rtmp streams

---

FilterPlugin/src/main/java/io/antmedia/plugin/MCUManager.java

https://github.com/ant-media/Ant-Media-Server/issues/3902

Add suffix to merged stream id

---

FilterPlugin/src/main/java/io/antmedia/plugin/MCUManager.java
FilterPlugin/src/test/java/io/antmedia/test/MCUManagerUnitTest.java

https://github.com/ant-media/Ant-Media-Server/issues/3997

Fix  MCU stream creation in the left room

---

FilterPlugin/src/main/java/io/antmedia/plugin/MCUManager.java
FilterPlugin/src/test/java/io/antmedia/test/MCUManagerUnitTest.java

https://github.com/ant-media/Ant-Media-Server/issues/3644

Close MCU Broadcast for Non-Zombi Rooms

---

FilterPlugin/src/main/java/io/antmedia/filter/FilterAdaptor.java
FilterPlugin/src/main/java/io/antmedia/filter/OpusDecoder.java
FilterPlugin/src/main/java/io/antmedia/plugin/MCUManager.java
FilterPlugin/src/main/java/io/antmedia/rest/FilterRestService.java
FilterPlugin/src/test/java/io/antmedia/test/MCUManagerUnitTest.java

https://github.com/ant-media/Ant-Media-Server/issues/4392

Cluster collector

---

README.md

https://github.com/ant-media/Ant-Media-Server/issues/4477

Add compatibility to readme

---

FilterPlugin/src/main/java/io/antmedia/filter/FilterAdaptor.java
FilterPlugin/src/main/java/io/antmedia/filter/VideoDecoder.java
FilterPlugin/src/test/java/io/antmedia/test/FilterAdaptorUnitTest.java

decode audio only if stream is hosted by another node

---

FilterPlugin/src/main/java/io/antmedia/filter/FilterAdaptor.java

https://github.com/ant-media/Ant-Media-Server/issues/4557

Keep the original pts in sync mode

---

.travis.yml
FilterPlugin/src/main/java/io/antmedia/filter/FilterAdaptor.java
FilterPlugin/src/main/java/io/antmedia/plugin/FiltersManager.java
FilterPlugin/src/main/java/io/antmedia/plugin/MCUManager.java
FilterPlugin/src/main/java/io/antmedia/rest/FilterRestService.java
FilterPlugin/src/test/java/io/antmedia/test/FilterAdaptorUnitTest.java
FilterPlugin/src/test/java/io/antmedia/test/FilterManagerUnitTest.java
FilterPlugin/src/test/java/io/antmedia/test/FilterRestServiceUnitTest.java
FilterPlugin/src/test/java/io/antmedia/test/MCUManagerUnitTest.java

https://github.com/ant-media/Ant-Media-Server/issues/4605
https://github.com/ant-media/Ant-Media-Server/issues/4580
Fix https://github.com/ant-media/Ant-Media-Server/issues/4541

Fix non-streaming issues in filter adaptor

---

.travis.yml
FilterPlugin/src/main/java/io/antmedia/filter/FilterAdaptor.java
FilterPlugin/src/main/java/io/antmedia/filter/OpusDecoder.java
FilterPlugin/src/main/java/io/antmedia/filter/Utils.java
FilterPlugin/src/main/java/io/antmedia/filter/utils/Filter.java
FilterPlugin/src/test/java/io/antmedia/test/FilterAdaptorUnitTest.java
FilterPlugin/src/test/java/io/antmedia/test/FilterGraphUnitTest.java
FilterPlugin/src/test/java/io/antmedia/test/OpusDecoderTest.java
FilterPlugin/src/test/java/io/antmedia/test/UtilsTest.java
ZixiPlugin/src/main/java/io/antmedia/zixi/ZixiClient.java

https://github.com/ant-media/Ant-Media-Server/issues/4520

Ffmpeg update

---

WebpageRecordingPlugin/README.md
WebpageRecordingPlugin/build/media_push.html

https://github.com/ant-media/Ant-Media-Server/issues/5252

Media Push Feature

---

MediaPushPlugin/README.md
MediaPushPlugin/src/main/java/io/antmedia/plugin/MediaPushPlugin.java

https://github.com/ant-media/Ant-Media-Server/issues/5609

Media Push disable no user gesture required policy for autoplay video

---

.travis.yml
FilterPlugin/pom.xml
FilterPlugin/src/main/java/io/antmedia/rest/FilterRestService.java
FilterPlugin/src/test/java/io/antmedia/test/FilterAdaptorUnitTest.java
FilterPlugin/src/test/java/io/antmedia/test/FilterRestServiceUnitTest.java
MediaPushPlugin/pom.xml
MediaPushPlugin/src/main/java/io/antmedia/rest/RestService.java
PythonWrapperPlugin/pom.xml
PythonWrapperPlugin/src/main/java/io/antmedia/rest/RestService.java
SamplePlugin/pom.xml
SamplePlugin/src/main/java/io/antmedia/rest/RestService.java
TensorflowPlugin/pom.xml
TensorflowPlugin/src/main/java/io/antmedia/rest/RestService.java
TimeCodeExtractor/pom.xml
TimeCodeExtractor/src/main/java/io/antmedia/rest/RestService.java
ZixiPlugin/pom.xml
ZixiPlugin/src/main/java/io/antmedia/plugin/ZixiPlugin.java
ZixiPlugin/src/main/java/io/antmedia/rest/ZixiRestService.java

https://github.com/ant-media/Ant-Media-Server/issues/5807

Upgrade java17

---

MediaPushPlugin/src/main/script/install_media-push-plugin.sh

It's added for the cloudformation script users.

Accept installing chrome automatically in media push script

---

FilterPlugin/pom.xml
FilterPlugin/src/main/java/io/antmedia/rest/FilterRestService.java
TensorflowPlugin/src/main/java/io/antmedia/rest/RestService.java

https://github.com/ant-media/Ant-Media-Server/issues/6060

Enable OpenAPI

---

FilterPlugin/src/main/java/io/antmedia/plugin/MCUManager.java
FilterPlugin/src/test/java/io/antmedia/test/MCUManagerUnitTest.java

https://github.com/ant-media/Ant-Media-Server/issues/5755

Refactor remove conference from db

---

.travis.yml
MediaPushPlugin/src/main/java/io/antmedia/rest/RestService.java
MediaPushPlugin/src/test/java/io/antmedia/rest/RestServiceUnitTest.java

https://github.com/ant-media/Ant-Media-Server/issues/6430

Fix Media Push is not working on K8

---

ClipCreatorPlugin/src/main/java/io/antmedia/plugin/ClipCreatorConverter.java
ClipCreatorPlugin/src/main/java/io/antmedia/plugin/ClipCreatorPlugin.java
ClipCreatorPlugin/src/main/java/io/antmedia/plugin/ClipCreatorSettings.java
ClipCreatorPlugin/src/main/java/io/antmedia/rest/ClipCreatorRestService.java
ClipCreatorPlugin/src/test/java/io/antmedia/test/integration/ClipCreatorPluginIntegrationTest.java
ClipCreatorPlugin/src/test/java/io/antmedia/test/plugin/ClipCreatorPluginTest.java

https://github.com/ant-media/Ant-Media-Server/issues/6996

Add flag to delete ts files and REST Method to delete mp4 not in database

---

ClipCreatorPlugin/.gitignore
FilterPlugin/src/main/java/io/antmedia/filter/utils/FilterGraph.java

https://github.com/ant-media/Ant-Media-Server/issues/7166

Change log level from info to debug

---

FilterPlugin/src/main/java/io/antmedia/filter/FilterAdaptor.java
FilterPlugin/src/main/java/io/antmedia/filter/utils/FilterGraph.java

https://github.com/ant-media/Ant-Media-Server/issues/7069

Add reason to filter graph creation request's answer

---

FilterPlugin/src/main/java/io/antmedia/filter/FilterAdaptor.java

[#7251](https://github.com/ant-media/Ant-Media-Server/issues/7251)

LL-HLS is not working with Filter Plugin stream

---

FilterPlugin/src/main/java/io/antmedia/filter/FilterAdaptor.java

https://github.com/ant-media/Ant-Media-Server/issues/7293

Add query parameters  to startPublish 

---

MediaPushPlugin/src/main/script/install_media-push-plugin.sh

https://github.com/ant-media/Ant-Media-Server/issues/7433

Change releaseUrl to Maven Central repository

---

MediaPushPlugin/src/main/script/install_media-push-plugin.sh

https://github.com/ant-media/Ant-Media-Server/issues/7460

Update media-push plugin download to use Maven Central URL

---

MediaPushPlugin/src/main/script/install_media-push-plugin.sh

https://github.com/ant-media/Ant-Media-Server/issues/7460

Fix download url for snapshot
